2019-12-11 14:05:45.806|INFO|DUMP EXCEPTION
[cubrid.jdbc.jci.UJciException]
ER_DBMS[-493,Syntax: Syntax error: unexpected END OF STATEMENT ]
	at cubrid.jdbc.jci.UConnection.createJciException(UConnection.java:2220)
	at cubrid.jdbc.jci.UInputBuffer.<init>(UInputBuffer.java:127)
	at cubrid.jdbc.jci.UConnection.send_recv_msg(UConnection.java:1785)
	at cubrid.jdbc.jci.UConnection.send_recv_msg(UConnection.java:1797)
	at cubrid.jdbc.jci.UConnection.prepareInternal(UConnection.java:997)
	at cubrid.jdbc.jci.UConnection.prepare(UConnection.java:1035)
	at cubrid.jdbc.jci.UConnection.prepare(UConnection.java:1016)
	at cubrid.jdbc.driver.CUBRIDConnection.prepare(CUBRIDConnection.java:646)
	at cubrid.jdbc.driver.CUBRIDStatement.prepare(CUBRIDStatement.java:1110)
	at cubrid.jdbc.driver.CUBRIDStatement.executeUpdate(CUBRIDStatement.java:633)
	at cubrid.jdbc.driver.CUBRIDStatement.executeUpdate(CUBRIDStatement.java:258)
	at ch.enterag.utils.jdbc.BaseStatement.executeUpdate(BaseStatement.java:72)
	at ch.admin.bar.siard2.jdbc.CUBRIDStatement.executeUpdate(CUBRIDStatement.java:193)
	at ch.admin.bar.siard2.cmd.MetaDataToDb.dropTables(MetaDataToDb.java:764)
	at ch.admin.bar.siard2.cmd.MetaDataToDb.upload(MetaDataToDb.java:868)
	at ch.admin.bar.siard2.gui.tasks.UploadTask.call(UploadTask.java:64)
	at ch.admin.bar.siard2.gui.tasks.UploadTask.call(UploadTask.java:1)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
2019-12-11 14:05:45.809|INFO|DUMP EXCEPTION
[cubrid.jdbc.jci.UJciException]
ER_DBMS[-493,Syntax: Syntax error: unexpected END OF STATEMENT ]
	at cubrid.jdbc.jci.UConnection.createJciException(UConnection.java:2220)
	at cubrid.jdbc.jci.UInputBuffer.<init>(UInputBuffer.java:127)
	at cubrid.jdbc.jci.UConnection.send_recv_msg(UConnection.java:1785)
	at cubrid.jdbc.jci.UConnection.send_recv_msg(UConnection.java:1797)
	at cubrid.jdbc.jci.UConnection.prepareInternal(UConnection.java:997)
	at cubrid.jdbc.jci.UConnection.prepare(UConnection.java:1035)
	at cubrid.jdbc.jci.UConnection.prepare(UConnection.java:1016)
	at cubrid.jdbc.driver.CUBRIDConnection.prepare(CUBRIDConnection.java:646)
	at cubrid.jdbc.driver.CUBRIDStatement.prepare(CUBRIDStatement.java:1110)
	at cubrid.jdbc.driver.CUBRIDStatement.executeUpdate(CUBRIDStatement.java:633)
	at cubrid.jdbc.driver.CUBRIDStatement.executeUpdate(CUBRIDStatement.java:258)
	at ch.enterag.utils.jdbc.BaseStatement.executeUpdate(BaseStatement.java:72)
	at ch.admin.bar.siard2.jdbc.CUBRIDStatement.executeUpdate(CUBRIDStatement.java:193)
	at ch.admin.bar.siard2.cmd.MetaDataToDb.dropTables(MetaDataToDb.java:764)
	at ch.admin.bar.siard2.cmd.MetaDataToDb.upload(MetaDataToDb.java:868)
	at ch.admin.bar.siard2.gui.tasks.UploadTask.call(UploadTask.java:64)
	at ch.admin.bar.siard2.gui.tasks.UploadTask.call(UploadTask.java:1)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
2019-12-11 14:05:45.810|INFO|DUMP EXCEPTION
[cubrid.jdbc.driver.CUBRIDException]
cubrid.jdbc.driver.CUBRIDException: Syntax: Syntax error: unexpected END OF STATEMENT [CAS INFO-localhost:30000,1,11416],[SESSION-128035],[URL-jdbc:cubrid:localhost:30000:ARCHIVE_UP:DBA:********:?charset=utf8].
	at cubrid.jdbc.jci.UConnection.createJciException(UConnection.java:2220)
	at cubrid.jdbc.jci.UInputBuffer.<init>(UInputBuffer.java:127)
	at cubrid.jdbc.jci.UConnection.send_recv_msg(UConnection.java:1785)
	at cubrid.jdbc.jci.UConnection.send_recv_msg(UConnection.java:1797)
	at cubrid.jdbc.jci.UConnection.prepareInternal(UConnection.java:997)
	at cubrid.jdbc.jci.UConnection.prepare(UConnection.java:1035)
	at cubrid.jdbc.jci.UConnection.prepare(UConnection.java:1016)
	at cubrid.jdbc.driver.CUBRIDConnection.prepare(CUBRIDConnection.java:646)
	at cubrid.jdbc.driver.CUBRIDStatement.prepare(CUBRIDStatement.java:1110)
	at cubrid.jdbc.driver.CUBRIDStatement.executeUpdate(CUBRIDStatement.java:633)
	at cubrid.jdbc.driver.CUBRIDStatement.executeUpdate(CUBRIDStatement.java:258)
	at ch.enterag.utils.jdbc.BaseStatement.executeUpdate(BaseStatement.java:72)
	at ch.admin.bar.siard2.jdbc.CUBRIDStatement.executeUpdate(CUBRIDStatement.java:193)
	at ch.admin.bar.siard2.cmd.MetaDataToDb.dropTables(MetaDataToDb.java:764)
	at ch.admin.bar.siard2.cmd.MetaDataToDb.upload(MetaDataToDb.java:868)
	at ch.admin.bar.siard2.gui.tasks.UploadTask.call(UploadTask.java:64)
	at ch.admin.bar.siard2.gui.tasks.UploadTask.call(UploadTask.java:1)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
2019-12-11 14:05:46.711|INFO|DUMP EXCEPTION
[cubrid.jdbc.jci.UJciException]
ER_DBMS[-494,Semantic: before ' (
      "ID" DECIMAL(11) NOT NULL,
      "COURSE_ID" DECIMA...'
Class TB_COURSE_USERS already exists. create class TB_COURSE_USERS ( ID numeric(11,0) not null , C...]
	at cubrid.jdbc.jci.UConnection.createJciException(UConnection.java:2220)
	at cubrid.jdbc.jci.UInputBuffer.<init>(UInputBuffer.java:127)
	at cubrid.jdbc.jci.UConnection.send_recv_msg(UConnection.java:1785)
	at cubrid.jdbc.jci.UConnection.send_recv_msg(UConnection.java:1797)
	at cubrid.jdbc.jci.UConnection.prepareInternal(UConnection.java:997)
	at cubrid.jdbc.jci.UConnection.prepare(UConnection.java:1035)
	at cubrid.jdbc.jci.UConnection.prepare(UConnection.java:1016)
	at cubrid.jdbc.driver.CUBRIDConnection.prepare(CUBRIDConnection.java:646)
	at cubrid.jdbc.driver.CUBRIDStatement.prepare(CUBRIDStatement.java:1110)
	at cubrid.jdbc.driver.CUBRIDStatement.executeUpdate(CUBRIDStatement.java:633)
	at cubrid.jdbc.driver.CUBRIDStatement.executeUpdate(CUBRIDStatement.java:258)
	at ch.enterag.utils.jdbc.BaseStatement.executeUpdate(BaseStatement.java:72)
	at ch.admin.bar.siard2.jdbc.CUBRIDStatement.executeUpdate(CUBRIDStatement.java:193)
	at ch.admin.bar.siard2.cmd.MetaDataToDb.createTable(MetaDataToDb.java:532)
	at ch.admin.bar.siard2.cmd.MetaDataToDb.createTables(MetaDataToDb.java:674)
	at ch.admin.bar.siard2.cmd.MetaDataToDb.upload(MetaDataToDb.java:871)
	at ch.admin.bar.siard2.gui.tasks.UploadTask.call(UploadTask.java:64)
	at ch.admin.bar.siard2.gui.tasks.UploadTask.call(UploadTask.java:1)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
2019-12-11 14:05:46.712|INFO|DUMP EXCEPTION
[cubrid.jdbc.jci.UJciException]
ER_DBMS[-494,Semantic: before ' (
      "ID" DECIMAL(11) NOT NULL,
      "COURSE_ID" DECIMA...'
Class TB_COURSE_USERS already exists. create class TB_COURSE_USERS ( ID numeric(11,0) not null , C...]
	at cubrid.jdbc.jci.UConnection.createJciException(UConnection.java:2220)
	at cubrid.jdbc.jci.UInputBuffer.<init>(UInputBuffer.java:127)
	at cubrid.jdbc.jci.UConnection.send_recv_msg(UConnection.java:1785)
	at cubrid.jdbc.jci.UConnection.send_recv_msg(UConnection.java:1797)
	at cubrid.jdbc.jci.UConnection.prepareInternal(UConnection.java:997)
	at cubrid.jdbc.jci.UConnection.prepare(UConnection.java:1035)
	at cubrid.jdbc.jci.UConnection.prepare(UConnection.java:1016)
	at cubrid.jdbc.driver.CUBRIDConnection.prepare(CUBRIDConnection.java:646)
	at cubrid.jdbc.driver.CUBRIDStatement.prepare(CUBRIDStatement.java:1110)
	at cubrid.jdbc.driver.CUBRIDStatement.executeUpdate(CUBRIDStatement.java:633)
	at cubrid.jdbc.driver.CUBRIDStatement.executeUpdate(CUBRIDStatement.java:258)
	at ch.enterag.utils.jdbc.BaseStatement.executeUpdate(BaseStatement.java:72)
	at ch.admin.bar.siard2.jdbc.CUBRIDStatement.executeUpdate(CUBRIDStatement.java:193)
	at ch.admin.bar.siard2.cmd.MetaDataToDb.createTable(MetaDataToDb.java:532)
	at ch.admin.bar.siard2.cmd.MetaDataToDb.createTables(MetaDataToDb.java:674)
	at ch.admin.bar.siard2.cmd.MetaDataToDb.upload(MetaDataToDb.java:871)
	at ch.admin.bar.siard2.gui.tasks.UploadTask.call(UploadTask.java:64)
	at ch.admin.bar.siard2.gui.tasks.UploadTask.call(UploadTask.java:1)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
2019-12-11 14:05:46.713|INFO|DUMP EXCEPTION
[cubrid.jdbc.driver.CUBRIDException]
cubrid.jdbc.driver.CUBRIDException: Semantic: before ' (
      "ID" DECIMAL(11) NOT NULL,
      "COURSE_ID" DECIMA...'
Class TB_COURSE_USERS already exists. create class TB_COURSE_USERS ( ID numeric(11,0) not null , C...[CAS INFO-localhost:30000,1,11416],[SESSION-128035],[URL-jdbc:cubrid:localhost:30000:ARCHIVE_UP:DBA:********:?charset=utf8].
	at cubrid.jdbc.jci.UConnection.createJciException(UConnection.java:2220)
	at cubrid.jdbc.jci.UInputBuffer.<init>(UInputBuffer.java:127)
	at cubrid.jdbc.jci.UConnection.send_recv_msg(UConnection.java:1785)
	at cubrid.jdbc.jci.UConnection.send_recv_msg(UConnection.java:1797)
	at cubrid.jdbc.jci.UConnection.prepareInternal(UConnection.java:997)
	at cubrid.jdbc.jci.UConnection.prepare(UConnection.java:1035)
	at cubrid.jdbc.jci.UConnection.prepare(UConnection.java:1016)
	at cubrid.jdbc.driver.CUBRIDConnection.prepare(CUBRIDConnection.java:646)
	at cubrid.jdbc.driver.CUBRIDStatement.prepare(CUBRIDStatement.java:1110)
	at cubrid.jdbc.driver.CUBRIDStatement.executeUpdate(CUBRIDStatement.java:633)
	at cubrid.jdbc.driver.CUBRIDStatement.executeUpdate(CUBRIDStatement.java:258)
	at ch.enterag.utils.jdbc.BaseStatement.executeUpdate(BaseStatement.java:72)
	at ch.admin.bar.siard2.jdbc.CUBRIDStatement.executeUpdate(CUBRIDStatement.java:193)
	at ch.admin.bar.siard2.cmd.MetaDataToDb.createTable(MetaDataToDb.java:532)
	at ch.admin.bar.siard2.cmd.MetaDataToDb.createTables(MetaDataToDb.java:674)
	at ch.admin.bar.siard2.cmd.MetaDataToDb.upload(MetaDataToDb.java:871)
	at ch.admin.bar.siard2.gui.tasks.UploadTask.call(UploadTask.java:64)
	at ch.admin.bar.siard2.gui.tasks.UploadTask.call(UploadTask.java:1)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
2019-12-11 14:05:56.186|INFO|DUMP EXCEPTION
[java.net.SocketException]
java.net.SocketException: Socket closed
	at java.net.SocketOutputStream.socketWrite(Unknown Source)
	at java.net.SocketOutputStream.write(Unknown Source)
	at java.io.DataOutputStream.write(Unknown Source)
	at java.io.DataOutputStream.write(Unknown Source)
	at cubrid.jdbc.util.ByteArrayBuffer.writeToStream(ByteArrayBuffer.java:136)
	at cubrid.jdbc.jci.UOutputBuffer.sendData(UOutputBuffer.java:74)
	at cubrid.jdbc.jci.UConnection.send_recv_msg(UConnection.java:1783)
	at cubrid.jdbc.jci.UConnection.send_recv_msg(UConnection.java:1797)
	at cubrid.jdbc.jci.UConnection.check_cas(UConnection.java:1494)
	at cubrid.jdbc.jci.UConnection.checkReconnect(UConnection.java:2108)
	at cubrid.jdbc.jci.UConnection.disconnect(UConnection.java:2151)
	at cubrid.jdbc.jci.UConnection.close(UConnection.java:521)
	at cubrid.jdbc.driver.CUBRIDConnection.close(CUBRIDConnection.java:266)
	at cubrid.jdbc.driver.CUBRIDConnection.finalize(CUBRIDConnection.java:939)
	at java.lang.System$2.invokeFinalize(Unknown Source)
	at java.lang.ref.Finalizer.runFinalizer(Unknown Source)
	at java.lang.ref.Finalizer.access$100(Unknown Source)
	at java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)
2019-12-11 14:05:56.187|INFO|DUMP EXCEPTION
[java.net.SocketException]
java.net.SocketException: Socket Closed
	at java.net.AbstractPlainSocketImpl.setOption(Unknown Source)
	at java.net.PlainSocketImpl.setOption(Unknown Source)
	at java.net.Socket.setSoLinger(Unknown Source)
	at cubrid.jdbc.jci.UConnection.clientSocketClose(UConnection.java:1769)
	at cubrid.jdbc.jci.UConnection.checkReconnect(UConnection.java:2109)
	at cubrid.jdbc.jci.UConnection.disconnect(UConnection.java:2151)
	at cubrid.jdbc.jci.UConnection.close(UConnection.java:521)
	at cubrid.jdbc.driver.CUBRIDConnection.close(CUBRIDConnection.java:266)
	at cubrid.jdbc.driver.CUBRIDConnection.finalize(CUBRIDConnection.java:939)
	at java.lang.System$2.invokeFinalize(Unknown Source)
	at java.lang.ref.Finalizer.runFinalizer(Unknown Source)
	at java.lang.ref.Finalizer.access$100(Unknown Source)
	at java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)
2019-12-11 14:06:05.294|INFO|DUMP EXCEPTION
[cubrid.jdbc.jci.UJciException]
ER_DBMS[-493,Syntax: Syntax error: unexpected END OF STATEMENT ]
	at cubrid.jdbc.jci.UConnection.createJciException(UConnection.java:2220)
	at cubrid.jdbc.jci.UInputBuffer.<init>(UInputBuffer.java:127)
	at cubrid.jdbc.jci.UConnection.send_recv_msg(UConnection.java:1785)
	at cubrid.jdbc.jci.UConnection.send_recv_msg(UConnection.java:1797)
	at cubrid.jdbc.jci.UConnection.prepareInternal(UConnection.java:997)
	at cubrid.jdbc.jci.UConnection.prepare(UConnection.java:1035)
	at cubrid.jdbc.jci.UConnection.prepare(UConnection.java:1016)
	at cubrid.jdbc.driver.CUBRIDConnection.prepare(CUBRIDConnection.java:646)
	at cubrid.jdbc.driver.CUBRIDStatement.prepare(CUBRIDStatement.java:1110)
	at cubrid.jdbc.driver.CUBRIDStatement.executeUpdate(CUBRIDStatement.java:633)
	at cubrid.jdbc.driver.CUBRIDStatement.executeUpdate(CUBRIDStatement.java:258)
	at ch.enterag.utils.jdbc.BaseStatement.executeUpdate(BaseStatement.java:72)
	at ch.admin.bar.siard2.jdbc.CUBRIDStatement.executeUpdate(CUBRIDStatement.java:193)
	at ch.admin.bar.siard2.cmd.MetaDataToDb.dropTables(MetaDataToDb.java:764)
	at ch.admin.bar.siard2.cmd.MetaDataToDb.upload(MetaDataToDb.java:868)
	at ch.admin.bar.siard2.gui.tasks.UploadTask.call(UploadTask.java:64)
	at ch.admin.bar.siard2.gui.tasks.UploadTask.call(UploadTask.java:1)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
2019-12-11 14:06:05.295|INFO|DUMP EXCEPTION
[cubrid.jdbc.jci.UJciException]
ER_DBMS[-493,Syntax: Syntax error: unexpected END OF STATEMENT ]
	at cubrid.jdbc.jci.UConnection.createJciException(UConnection.java:2220)
	at cubrid.jdbc.jci.UInputBuffer.<init>(UInputBuffer.java:127)
	at cubrid.jdbc.jci.UConnection.send_recv_msg(UConnection.java:1785)
	at cubrid.jdbc.jci.UConnection.send_recv_msg(UConnection.java:1797)
	at cubrid.jdbc.jci.UConnection.prepareInternal(UConnection.java:997)
	at cubrid.jdbc.jci.UConnection.prepare(UConnection.java:1035)
	at cubrid.jdbc.jci.UConnection.prepare(UConnection.java:1016)
	at cubrid.jdbc.driver.CUBRIDConnection.prepare(CUBRIDConnection.java:646)
	at cubrid.jdbc.driver.CUBRIDStatement.prepare(CUBRIDStatement.java:1110)
	at cubrid.jdbc.driver.CUBRIDStatement.executeUpdate(CUBRIDStatement.java:633)
	at cubrid.jdbc.driver.CUBRIDStatement.executeUpdate(CUBRIDStatement.java:258)
	at ch.enterag.utils.jdbc.BaseStatement.executeUpdate(BaseStatement.java:72)
	at ch.admin.bar.siard2.jdbc.CUBRIDStatement.executeUpdate(CUBRIDStatement.java:193)
	at ch.admin.bar.siard2.cmd.MetaDataToDb.dropTables(MetaDataToDb.java:764)
	at ch.admin.bar.siard2.cmd.MetaDataToDb.upload(MetaDataToDb.java:868)
	at ch.admin.bar.siard2.gui.tasks.UploadTask.call(UploadTask.java:64)
	at ch.admin.bar.siard2.gui.tasks.UploadTask.call(UploadTask.java:1)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
2019-12-11 14:06:05.296|INFO|DUMP EXCEPTION
[cubrid.jdbc.driver.CUBRIDException]
cubrid.jdbc.driver.CUBRIDException: Syntax: Syntax error: unexpected END OF STATEMENT [CAS INFO-localhost:30000,1,11416],[SESSION-128041],[URL-jdbc:cubrid:localhost:30000:ARCHIVE_UP:DBA:********:?charset=utf8].
	at cubrid.jdbc.jci.UConnection.createJciException(UConnection.java:2220)
	at cubrid.jdbc.jci.UInputBuffer.<init>(UInputBuffer.java:127)
	at cubrid.jdbc.jci.UConnection.send_recv_msg(UConnection.java:1785)
	at cubrid.jdbc.jci.UConnection.send_recv_msg(UConnection.java:1797)
	at cubrid.jdbc.jci.UConnection.prepareInternal(UConnection.java:997)
	at cubrid.jdbc.jci.UConnection.prepare(UConnection.java:1035)
	at cubrid.jdbc.jci.UConnection.prepare(UConnection.java:1016)
	at cubrid.jdbc.driver.CUBRIDConnection.prepare(CUBRIDConnection.java:646)
	at cubrid.jdbc.driver.CUBRIDStatement.prepare(CUBRIDStatement.java:1110)
	at cubrid.jdbc.driver.CUBRIDStatement.executeUpdate(CUBRIDStatement.java:633)
	at cubrid.jdbc.driver.CUBRIDStatement.executeUpdate(CUBRIDStatement.java:258)
	at ch.enterag.utils.jdbc.BaseStatement.executeUpdate(BaseStatement.java:72)
	at ch.admin.bar.siard2.jdbc.CUBRIDStatement.executeUpdate(CUBRIDStatement.java:193)
	at ch.admin.bar.siard2.cmd.MetaDataToDb.dropTables(MetaDataToDb.java:764)
	at ch.admin.bar.siard2.cmd.MetaDataToDb.upload(MetaDataToDb.java:868)
	at ch.admin.bar.siard2.gui.tasks.UploadTask.call(UploadTask.java:64)
	at ch.admin.bar.siard2.gui.tasks.UploadTask.call(UploadTask.java:1)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
2019-12-11 14:06:05.624|INFO|DUMP EXCEPTION
[cubrid.jdbc.jci.UJciException]
ER_DBMS[-494,Semantic: before ' (
      "ID" DECIMAL(11) NOT NULL,
      "COURSE_ID" DECIMA...'
Class TB_COURSE_USERS already exists. create class TB_COURSE_USERS ( ID numeric(11,0) not null , C...]
	at cubrid.jdbc.jci.UConnection.createJciException(UConnection.java:2220)
	at cubrid.jdbc.jci.UInputBuffer.<init>(UInputBuffer.java:127)
	at cubrid.jdbc.jci.UConnection.send_recv_msg(UConnection.java:1785)
	at cubrid.jdbc.jci.UConnection.send_recv_msg(UConnection.java:1797)
	at cubrid.jdbc.jci.UConnection.prepareInternal(UConnection.java:997)
	at cubrid.jdbc.jci.UConnection.prepare(UConnection.java:1035)
	at cubrid.jdbc.jci.UConnection.prepare(UConnection.java:1016)
	at cubrid.jdbc.driver.CUBRIDConnection.prepare(CUBRIDConnection.java:646)
	at cubrid.jdbc.driver.CUBRIDStatement.prepare(CUBRIDStatement.java:1110)
	at cubrid.jdbc.driver.CUBRIDStatement.executeUpdate(CUBRIDStatement.java:633)
	at cubrid.jdbc.driver.CUBRIDStatement.executeUpdate(CUBRIDStatement.java:258)
	at ch.enterag.utils.jdbc.BaseStatement.executeUpdate(BaseStatement.java:72)
	at ch.admin.bar.siard2.jdbc.CUBRIDStatement.executeUpdate(CUBRIDStatement.java:193)
	at ch.admin.bar.siard2.cmd.MetaDataToDb.createTable(MetaDataToDb.java:532)
	at ch.admin.bar.siard2.cmd.MetaDataToDb.createTables(MetaDataToDb.java:674)
	at ch.admin.bar.siard2.cmd.MetaDataToDb.upload(MetaDataToDb.java:871)
	at ch.admin.bar.siard2.gui.tasks.UploadTask.call(UploadTask.java:64)
	at ch.admin.bar.siard2.gui.tasks.UploadTask.call(UploadTask.java:1)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
2019-12-11 14:06:05.624|INFO|DUMP EXCEPTION
[cubrid.jdbc.jci.UJciException]
ER_DBMS[-494,Semantic: before ' (
      "ID" DECIMAL(11) NOT NULL,
      "COURSE_ID" DECIMA...'
Class TB_COURSE_USERS already exists. create class TB_COURSE_USERS ( ID numeric(11,0) not null , C...]
	at cubrid.jdbc.jci.UConnection.createJciException(UConnection.java:2220)
	at cubrid.jdbc.jci.UInputBuffer.<init>(UInputBuffer.java:127)
	at cubrid.jdbc.jci.UConnection.send_recv_msg(UConnection.java:1785)
	at cubrid.jdbc.jci.UConnection.send_recv_msg(UConnection.java:1797)
	at cubrid.jdbc.jci.UConnection.prepareInternal(UConnection.java:997)
	at cubrid.jdbc.jci.UConnection.prepare(UConnection.java:1035)
	at cubrid.jdbc.jci.UConnection.prepare(UConnection.java:1016)
	at cubrid.jdbc.driver.CUBRIDConnection.prepare(CUBRIDConnection.java:646)
	at cubrid.jdbc.driver.CUBRIDStatement.prepare(CUBRIDStatement.java:1110)
	at cubrid.jdbc.driver.CUBRIDStatement.executeUpdate(CUBRIDStatement.java:633)
	at cubrid.jdbc.driver.CUBRIDStatement.executeUpdate(CUBRIDStatement.java:258)
	at ch.enterag.utils.jdbc.BaseStatement.executeUpdate(BaseStatement.java:72)
	at ch.admin.bar.siard2.jdbc.CUBRIDStatement.executeUpdate(CUBRIDStatement.java:193)
	at ch.admin.bar.siard2.cmd.MetaDataToDb.createTable(MetaDataToDb.java:532)
	at ch.admin.bar.siard2.cmd.MetaDataToDb.createTables(MetaDataToDb.java:674)
	at ch.admin.bar.siard2.cmd.MetaDataToDb.upload(MetaDataToDb.java:871)
	at ch.admin.bar.siard2.gui.tasks.UploadTask.call(UploadTask.java:64)
	at ch.admin.bar.siard2.gui.tasks.UploadTask.call(UploadTask.java:1)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
2019-12-11 14:06:05.625|INFO|DUMP EXCEPTION
[cubrid.jdbc.driver.CUBRIDException]
cubrid.jdbc.driver.CUBRIDException: Semantic: before ' (
      "ID" DECIMAL(11) NOT NULL,
      "COURSE_ID" DECIMA...'
Class TB_COURSE_USERS already exists. create class TB_COURSE_USERS ( ID numeric(11,0) not null , C...[CAS INFO-localhost:30000,1,11416],[SESSION-128041],[URL-jdbc:cubrid:localhost:30000:ARCHIVE_UP:DBA:********:?charset=utf8].
	at cubrid.jdbc.jci.UConnection.createJciException(UConnection.java:2220)
	at cubrid.jdbc.jci.UInputBuffer.<init>(UInputBuffer.java:127)
	at cubrid.jdbc.jci.UConnection.send_recv_msg(UConnection.java:1785)
	at cubrid.jdbc.jci.UConnection.send_recv_msg(UConnection.java:1797)
	at cubrid.jdbc.jci.UConnection.prepareInternal(UConnection.java:997)
	at cubrid.jdbc.jci.UConnection.prepare(UConnection.java:1035)
	at cubrid.jdbc.jci.UConnection.prepare(UConnection.java:1016)
	at cubrid.jdbc.driver.CUBRIDConnection.prepare(CUBRIDConnection.java:646)
	at cubrid.jdbc.driver.CUBRIDStatement.prepare(CUBRIDStatement.java:1110)
	at cubrid.jdbc.driver.CUBRIDStatement.executeUpdate(CUBRIDStatement.java:633)
	at cubrid.jdbc.driver.CUBRIDStatement.executeUpdate(CUBRIDStatement.java:258)
	at ch.enterag.utils.jdbc.BaseStatement.executeUpdate(BaseStatement.java:72)
	at ch.admin.bar.siard2.jdbc.CUBRIDStatement.executeUpdate(CUBRIDStatement.java:193)
	at ch.admin.bar.siard2.cmd.MetaDataToDb.createTable(MetaDataToDb.java:532)
	at ch.admin.bar.siard2.cmd.MetaDataToDb.createTables(MetaDataToDb.java:674)
	at ch.admin.bar.siard2.cmd.MetaDataToDb.upload(MetaDataToDb.java:871)
	at ch.admin.bar.siard2.gui.tasks.UploadTask.call(UploadTask.java:64)
	at ch.admin.bar.siard2.gui.tasks.UploadTask.call(UploadTask.java:1)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
